### ISSUE TITLE
error: subprocess-exited-with-error

### ISSUE THREAD

**Issue by yksu** [JonathanWenger/itergp#3]
I download the new package for itergp, and execute the command pip install.
Then, it shows the error "error: subprocess-exited-with-error".

The complete execution show below:

```
Processing /Users/suyunkuan/Desktop/ML_Numerics for Machine Learning/Exercise/Ex2/itergp
Installing build dependencies ... done
Getting requirements to build wheel ... done
Installing backend dependencies ... done
Preparing metadata (pyproject.toml) ... done
Collecting probnum@ git+https://github.com/marvinpfoertner/probnum.git@ad-prototype
Cloning https://github.com/marvinpfoertner/probnum.git (to revision ad-prototype) to /private/var/folders/vw/0wr8h_mx7t754p2l19b2mc_r0000gn/T/pip-install-ibzys1gc/probnum_ba67848f910146c89ae6e3683faa4cbe
Running command git clone --filter=blob:none --quiet https://github.com/marvinpfoertner/probnum.git /private/var/folders/vw/0wr8h_mx7t754p2l19b2mc_r0000gn/T/pip-install-ibzys1gc/probnum_ba67848f910146c89ae6e3683faa4cbe
Running command git checkout -b ad-prototype --track origin/ad-prototype
Switched to a new branch 'ad-prototype'
branch 'ad-prototype' set up to track 'origin/ad-prototype'.
Resolved https://github.com/marvinpfoertner/probnum.git to commit bff243f58f2a7f5aa9060a973559b3b4e6ef6db1
Installing build dependencies ... done
Getting requirements to build wheel ... error
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> [47 lines of output]
Error in sitecustomize; set PYTHONVERBOSE for traceback:
AssertionError:
/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for [tool.setuptools] in pyproject.toml is still beta.
warnings.warn(msg, _BetaConfiguration)
Traceback (most recent call last):
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in 
main()
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
return hook(config_settings)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
self.run_setup()
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
exec(code, locals())
File "", line 33, in 
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/init.py", line 87, in setup
return distutils.core.setup(**attrs)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
dist.parse_config_files()
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 868, in parse_config_files
pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
config = read_configuration(filepath, True, ignore_option_errors, dist)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 140, in read_configuration
return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 195, in expand_configuration
return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 242, in expand
self._expand_all_dynamic(dist, package_dir)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 286, in _expand_all_dynamic
version=self._obtain_version(dist, package_dir),
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 332, in _obtain_version
return _expand.version(self._obtain(dist, "version", package_dir))
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 321, in _obtain
return self._expand_directive(
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 315, in _expand_directive
return _expand.read_attr(directive["attr"], package_dir, root_dir)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/expand.py", line 187, in read_attr
spec = _find_spec(module_name, path)
File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/expand.py", line 199, in _find_spec
spec = spec or importlib.util.find_spec(module_name)
File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/util.py", line 94, in find_spec
parent = import(parent_name, fromlist=['path'])
ModuleNotFoundError: No module named 'probnum'
[end of output]

note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by JonathanWenger** [comment]
What's the output of the command:
```
pip install git+https://github.com/marvinpfoertner/probnum.git@ad-prototype
```

**Comment by yksu** [comment]
After executing "pip install git+https://github.com/marvinpfoertner/probnum.git@ad-prototype
"
There error remains: 
Collecting git+https://github.com/marvinpfoertner/probnum.git@ad-prototype
  Cloning https://github.com/marvinpfoertner/probnum.git (to revision ad-prototype) to /private/var/folders/vw/0wr8h_mx7t754p2l19b2mc_r0000gn/T/pip-req-build-am0w8jy4
  Running command git clone --filter=blob:none --quiet https://github.com/marvinpfoertner/probnum.git /private/var/folders/vw/0wr8h_mx7t754p2l19b2mc_r0000gn/T/pip-req-build-am0w8jy4
  Running command git checkout -b ad-prototype --track origin/ad-prototype
  Switched to a new branch 'ad-prototype'
  branch 'ad-prototype' set up to track 'origin/ad-prototype'.
  Resolved https://github.com/marvinpfoertner/probnum.git to commit bff243f58f2a7f5aa9060a973559b3b4e6ef6db1
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      /opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 868, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 140, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 195, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 242, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 286, in _expand_all_dynamic
          version=self._obtain_version(dist, package_dir),
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 332, in _obtain_version
          return _expand.version(self._obtain(dist, "version", package_dir))
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 321, in _obtain
          return self._expand_directive(
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 315, in _expand_directive
          return _expand.read_attr(directive["attr"], package_dir, root_dir)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/expand.py", line 187, in read_attr
          spec = _find_spec(module_name, path)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/expand.py", line 199, in _find_spec
          spec = spec or importlib.util.find_spec(module_name)
        File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
      ModuleNotFoundError: No module named 'probnum'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JonathanWenger** [comment]
What's your setuptools version, i.e. the output of the command

```
pip show setuptools
```

**Comment by yksu** [comment]
pip show setuptools
Name: setuptools
Version: 65.4.1
Summary: Easily download, build, install, upgrade, and uninstall Python packages
Home-page: https://github.com/pypa/setuptools
Author: Python Packaging Authority
Author-email: distutils-sig@python.org
License: 
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: 
Required-by:

**Comment by JonathanWenger** [comment]
what about 
```
pip show wheel
```

**Comment by JonathanWenger** [comment]
I'm trying reproduce the error locally, but can't yet.

**Comment by yksu** [comment]
pip show wheel

Name: wheel
Version: 0.37.1
Summary: A built-package format for Python
Home-page: https://github.com/pypa/wheel
Author: Daniel Holth
Author-email: dholth@fastmail.fm
License: MIT
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: 
Required-by:

**Comment by JonathanWenger** [comment]
Try downgrading setuptools and reinstalling probnum:
```
pip uninstall setuptools
pip install setuptools==64.0
pip install git+https://github.com/marvinpfoertner/probnum.git@ad-prototype
```
any better? I assume you are on mac?

**Comment by yksu** [comment]
yes, I'm working on Mac

**Comment by yksu** [comment]
Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [47 lines of output]
      Error in sitecustomize; set PYTHONVERBOSE for traceback:
      AssertionError:
      /opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py:108: _BetaConfiguration: Support for `[tool.setuptools]` in `pyproject.toml` is still *beta*.
        warnings.warn(msg, _BetaConfiguration)
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 337, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 319, in _get_build_requires
          self.run_setup()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/build_meta.py", line 334, in run_setup
          exec(code, locals())
        File "<string>", line 33, in <module>
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
          return distutils.core.setup(**attrs)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 159, in setup
          dist.parse_config_files()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/dist.py", line 868, in parse_config_files
          pyprojecttoml.apply_configuration(self, filename, ignore_option_errors)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 62, in apply_configuration
          config = read_configuration(filepath, True, ignore_option_errors, dist)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 140, in read_configuration
          return expand_configuration(asdict, root_dir, ignore_option_errors, dist)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 195, in expand_configuration
          return _ConfigExpander(config, root_dir, ignore_option_errors, dist).expand()
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 242, in expand
          self._expand_all_dynamic(dist, package_dir)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 286, in _expand_all_dynamic
          version=self._obtain_version(dist, package_dir),
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 332, in _obtain_version
          return _expand.version(self._obtain(dist, "version", package_dir))
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 321, in _obtain
          return self._expand_directive(
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/pyprojecttoml.py", line 315, in _expand_directive
          return _expand.read_attr(directive["attr"], package_dir, root_dir)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/expand.py", line 188, in read_attr
          spec = _find_spec(module_name, path)
        File "/opt/homebrew/lib/python3.10/site-packages/setuptools/config/expand.py", line 200, in _find_spec
          spec = spec or importlib.util.find_spec(module_name)
        File "/opt/homebrew/Cellar/python@3.10/3.10.8/Frameworks/Python.framework/Versions/3.10/lib/python3.10/importlib/util.py", line 94, in find_spec
          parent = __import__(parent_name, fromlist=['__path__'])
      ModuleNotFoundError: No module named 'probnum'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by JonathanWenger** [comment]
Did you create an isolated new environment for itergp? If yes, could you post the result of
```
pip freeze
```

**Comment by yksu** [comment]
pip freeze
anyio==3.6.2
appdirs==1.4.4
appnope==0.1.3
argon2-cffi==21.3.0
argon2-cffi-bindings==21.2.0
asttokens==2.1.0
attrs==22.1.0
backcall==0.2.0
backend==0.2.4.1
beautifulsoup4==4.11.1
bleach==5.0.1
certifi==2022.9.24
cffi==1.15.1
contourpy==1.0.5
cycler==0.11.0
debugpy==1.6.3
decorator==5.1.1
defusedxml==0.7.1
entrypoints==0.4
executing==1.2.0
fastjsonschema==2.16.2
fonttools==4.38.0
functions==0.7.0
idna==3.4
imageio==2.22.3
importlib-metadata==5.0.0
ipykernel==6.17.0
ipython==8.6.0
ipython-genutils==0.2.0
jedi==0.18.1
Jinja2==3.1.2
joblib==1.2.0
jsonschema==4.16.0
jupyter-server==1.21.0
jupyter_client==7.4.4
jupyter_core==4.11.2
jupyterlab-pygments==0.2.2
kiwisolver==1.4.4
MarkupSafe==2.1.1
matplotlib==3.6.1
matplotlib-inline==0.1.6
mistune==2.0.4
nbclassic==0.4.7
nbclient==0.7.0
nbconvert==7.2.3
nbformat==5.7.0
nest-asyncio==1.5.6
networkx==2.8.8
notebook==6.5.2
notebook_shim==0.2.0
numpy==1.23.4
packaging==21.3
pandas==1.5.1
pandocfilters==1.5.0
parso==0.8.3
pexpect==4.8.0
pickleshare==0.7.5
Pillow==9.3.0
prometheus-client==0.15.0
prompt-toolkit==3.0.31
psutil==5.9.3
ptyprocess==0.7.0
pure-eval==0.2.2
pycparser==2.21
pyee==8.2.2
Pygments==2.13.0
pyparsing==3.0.9
pyppeteer==1.0.2
pyrsistent==0.19.1
python-dateutil==2.8.2
pytz==2022.5
PyWavelets==1.4.1
pyzmq==24.0.1
randvars==0.0.17
scikit-image==0.19.3
scikit-learn==1.1.3
scipy==1.9.3
Send2Trash==1.8.0
six==1.16.0
sklearn==0.0
sniffio==1.3.0
soupsieve==2.3.2.post1
stack-data==0.6.0
terminado==0.17.0
threadpoolctl==3.1.0
tifffile==2022.10.10
tinycss2==1.2.1
tornado==6.2
tqdm==4.64.1
traitlets==5.5.0
tueplots==0.0.5
urllib3==1.26.12
wcwidth==0.2.5
webencodings==0.5.1
websocket-client==1.4.1
websockets==10.4
zipp==3.10.0

**Comment by JonathanWenger** [comment]
That's not a fresh environment, is it? There are some `sci-kit` packages which are not dependencies of `itergp`.

**Comment by yksu** [comment]
I can't even install itergp by pip

**Comment by yksu** [comment]
I cloning the package the my notebook, then execute pip install .
 but there is error

**Comment by JonathanWenger** [comment]
I understand, but are you trying to install into a fresh Python environment or into your system environment? There might be package clashes that are not possible for me to debug since I don't have access to your machine.

**Comment by yksu** [comment]
ok very thanks for help, or may I find you in person next week to solve it?

**Comment by JonathanWenger** [comment]
Sure, no problem. E-mail me and I can try to help.
